### ISSUE TITLE
Bot Will Not Start

### ISSUE THREAD

**Issue by mobbyg** [BankkRoll/streamer-alerts-discord-bot#2]
When I do the npm start command I am getting an error and it appears to me to be an issue with the token? But I just generated it. Am I missing a step that was not in the readme?

Here is the error I am seeing when I try and start. 

npm start

> streamer-alerts-bot@1.0.0 start
> node .

node:internal/modules/cjs/loader:1289
    throw err;
    ^

SyntaxError: /home/mobbyg/gitstuff/streamer-alerts-discord-bot/config.json: Unexpected token / in JSON at position 90
    at parse (<anonymous>)
    at Module._extensions..json (node:internal/modules/cjs/loader:1286:39)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/mobbyg/gitstuff/streamer-alerts-discord-bot/src/index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)

Node.js v18.13.0

**Comment by BankkRoll** [comment]
> When I do the npm start command I am getting an error and it appears to me to be an issue with the token? But I just generated it. Am I missing a step that was not in the readme?
> 
> Here is the error I am seeing when I try and start.
> 
> npm start
> 
> > streamer-alerts-bot@1.0.0 start
> > node .
> 
> node:internal/modules/cjs/loader:1289 throw err; ^
> 
> SyntaxError: /home/mobbyg/gitstuff/streamer-alerts-discord-bot/config.json: Unexpected token / in JSON at position 90 at parse () at Module._extensions..json (node:internal/modules/cjs/loader:1286:39) at Module.load (node:internal/modules/cjs/loader:1081:32) at Module._load (node:internal/modules/cjs/loader:922:12) at Module.require (node:internal/modules/cjs/loader:1105:19) at require (node:internal/modules/cjs/helpers:103:18) at Object. (/home/mobbyg/gitstuff/streamer-alerts-discord-bot/src/index.js:5:16) at Module._compile (node:internal/modules/cjs/loader:1218:14) at Module._extensions..js (node:internal/modules/cjs/loader:1272:10) at Module.load (node:internal/modules/cjs/loader:1081:32)
> 
> Node.js v18.13.0


Hey @mobbyg sorry just seeing issue, have you solved this? Seems its not finding a bot token. 

Steps to solve:
1 - Rename config.json.example to config.json
2 - Make sure you put your discord bot token in the config (KEEP THIS PRIVATE AND SAFE!!)

```
{
  "token": "xxxxxxxxxxxxxxxxxxxxxx",                                    // bot token
  "color": "#61CB2B",                                                           // embed color
  "footerText": "Developed By: Bankkroll",                          // embed footer text
  "footerIcon": "https://i.ibb.co/Bqs3jh7/6302741.png"     // embed footer icon
}
```
